version: "2.1"

services:
  vouchersapi:
    image: vouchersapi
    build: .
    ports:
      - 8080:80
    depends_on:
      - db
  db:
    image: microsoft/mssql-server-linux
    # ports:
    #   - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Pa$$w0rd
